export type ViewerAction =
  | 'open-file'
  | 'reload-document'
  | 'print-document'
  | 'export-diagnostics'
  | 'check-for-updates'
  | 'open-find'
  | 'open-command-palette'
  | 'show-shortcuts-help'
  | 'find-next'
  | 'find-previous'
  | 'close-active-tab'
  | 'activate-next-tab'
  | 'activate-previous-tab'
  | 'toggle-left-sidebar'
  | 'toggle-right-sidebar';
