name: Bug report
description: Report a reproducible bug
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide a minimal set of steps.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App version
      placeholder: 0.1.0-alpha.1
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS 15.3 / Windows 11 / Ubuntu 24.04
    validations:
      required: true
